### ISSUE TITLE
Error installing mmcv-full

### ISSUE THREAD

**Issue by caiocvsilva** [Cogito2012/DEAR#11]
Following the directions on the GitHub, when running the command:
``` 
pip install mmcv-full==1.2.1 -f https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.1/index.html
```
The command fails with the following error:
```
Looking in links: https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.1/index.html
Collecting mmcv-full==1.2.1
  Using cached mmcv-full-1.2.1.tar.gz (251 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      /tmp/pip-install-6jmensbp/mmcv-full_883ba128e6c24b62bdb5675c066a03d8/setup.py:8: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.Distribution().fetch_build_eggs(['Cython', 'numpy>=1.11.1'])
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6jmensbp/mmcv-full_883ba128e6c24b62bdb5675c066a03d8/setup.py", line 15, in <module>
          import torch
        File "/home/username/.conda/envs/mmaction/lib/python3.7/site-packages/torch/__init__.py", line 189, in <module>
          _load_global_deps()
        File "/home/username/.conda/envs/mmaction/lib/python3.7/site-packages/torch/__init__.py", line 142, in _load_global_deps
          ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
        File "/home/username/.conda/envs/mmaction/lib/python3.7/ctypes/__init__.py", line 364, in __init__
          self._handle = _dlopen(self._name, mode)
      OSError: /home/username/.conda/envs/mmaction/lib/python3.7/site-packages/torch/lib/../../../../libcublas.so.11: symbol free_gemm_select, version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Trying to install using the suggested --use-pep517, results in error again:
```
Looking in links: https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.1/index.html
Collecting mmcv-full==1.2.1
  Using cached mmcv-full-1.2.1.tar.gz (251 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      /home/username/.conda/envs/mmaction/bin/python: No module named pip
      /tmp/pip-install-wnszk78b/mmcv-full_641186a7621946769760a8dd87ff86a0/setup.py:8: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.Distribution().fetch_build_eggs(['Cython', 'numpy>=1.11.1'])
      Traceback (most recent call last):
        File "/tmp/pip-build-env-9fxmm81s/overlay/lib/python3.7/site-packages/setuptools/installer.py", line 96, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/home/username/.conda/envs/mmaction/lib/python3.7/subprocess.py", line 363, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/username/.conda/envs/mmaction/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmplek5d5rn', '--quiet', 'numpy>=1.11.1']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/home/username/.conda/envs/mmaction/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/username/.conda/envs/mmaction/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/username/.conda/envs/mmaction/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-9fxmm81s/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-9fxmm81s/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-9fxmm81s/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-9fxmm81s/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
        File "/tmp/pip-build-env-9fxmm81s/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 917, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/tmp/pip-build-env-9fxmm81s/overlay/lib/python3.7/site-packages/setuptools/installer.py", line 41, in _fetch_build_eggs
          replace_conflicting=True,
        File "/tmp/pip-build-env-9fxmm81s/overlay/lib/python3.7/site-packages/pkg_resources/__init__.py", line 828, in resolve
          req, best, replace_conflicting, env, installer, required_by, to_activate
        File "/tmp/pip-build-env-9fxmm81s/overlay/lib/python3.7/site-packages/pkg_resources/__init__.py", line 864, in _resolve_dist
          req, ws, installer, replace_conflicting=replace_conflicting
        File "/tmp/pip-build-env-9fxmm81s/overlay/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1133, in best_match
          return self.obtain(req, installer)
        File "/tmp/pip-build-env-9fxmm81s/overlay/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1145, in obtain
          return installer(requirement)
        File "/tmp/pip-build-env-9fxmm81s/overlay/lib/python3.7/site-packages/setuptools/installer.py", line 98, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/home/username/.conda/envs/mmaction/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmplek5d5rn', '--quiet', 'numpy>=1.11.1']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
``` 

Am I doing something wrong, or have the installation instructions changed?

**Comment by Cogito2012** [comment]
@caiocvsilva Seems like it's still the pip issue. Can you try to upgrade your pip, then uninstall mmcv-full, and finally re-install it by ignoring the cached package? For example:
```shell
pip install --upgrade --user pip
pip uninstall mmcv-full
pip install mmcv-full==1.2.1 --no-cache-dir -f https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.1/index.html
```

**Comment by caiocvsilva** [comment]
Thank you for the response, @Cogito2012 . But the error still happens:

![Screenshot from 2023-05-11 16-29-45](https://github.com/Cogito2012/DEAR/assets/8015073/e0ccfcb5-1176-42ca-927b-f7b4b970d61d)

**Comment by caiocvsilva** [comment]
Apparently, the problem was with the version of libraries and drivers on my machine. Testing on a different machine solve the problem.

**Comment by MengyuanChen21** [comment]
I met the same issue with you and the following link helped me solve the issue:
https://github.com/pytorch/pytorch/issues/51080
